name = "fpm"
version = "0.1.4"
license = "MIT"
author = "fpm maintainers"
maintainer = ""
copyright = "2020 fpm contributors"

[dependencies]
[dependencies.stdlib]
git = "https://github.com/lkedward/stdlib-fpm.git"
rev = "eadc8ad5eaf182adee04f1bd31624ad19b9eaf2c"

[dependencies.toml-f]
git = "https://github.com/toml-f/toml-f"
rev = "2f5eaba864ff630ba0c3791126a3f811b6e437f3"

[dependencies.M_CLI2]
git = "https://github.com/urbanjost/M_CLI2.git"
rev = "e59fb2bfcf36199f1af506f937b3849180454a0f"

[[test]]
name = "cli-test"
source-dir = "test/cli_test"
main = "cli_test.f90"

[[test]]
name = "new-test"
source-dir = "test/new_test"
main = "new_test.f90"

[[test]]
name = "fpm-test"
source-dir = "test/fpm_test"
main = "main.f90"

[[test]]
name = "help-test"
source-dir = "test/help_test"
main = "help_test.f90"
